### ISSUE TITLE
Ability to disable repeated notifications of "Connection to Pico lost"

### ISSUE THREAD

**Issue by sgbaird** [paulober/MicroPico#193] opened 2024-01-29 18:27 UTC
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.

The following message (bottom-right corner) pops up over and over again when I don't have a Pico W connected. The message is pretty distracting, especially since it "pops up" again, instead of just staying there. If I click "X" on a notification, it just comes back again.

![image](https://github.com/paulober/MicroPico/assets/45469701/7a2358ee-1db3-4cd9-ba39-c888ae1e9d31)

Even when I click "Turn notifications off" it still pops up with the message:

![image](https://github.com/paulober/MicroPico/assets/45469701/2dd36de2-9044-4cbf-bafc-795fa769e532)

## Describe the solution you'd like

Create an option to disable these notifications/popups. In my case, it's pretty clear whether the Pico W is connected vs. disconnected based on the status bar icon, though I see how it would be generally useful to know if it has disconnected when that isn't the user's intention.

## Describe alternatives you've considered

I've ended up disabling and reenabling the entire extension on a per-workspace basis.

**Comment by vbakke** [comment] 2024-02-13 19:44
I agree. This is a really annoying repetitive warning. One warning when I disconnect the cable is fine. But it reappears every 7.5 seconds.

I use MicroPico v3.7.4 on a Windows VS Code 1.86.1

**Comment by sgbaird** [comment] 2024-02-13 20:39
@vbakke Since I'm still doing a fair bit of development off-and-on with the Pico W, I've decided to just connect one to make the warning go away.. 🫠

**Comment by vbakke** [comment] 2024-02-14 15:53
One way of solving it, I guess. 

Hard for me to know if the problem (or the solution) lies in [MicroPython (blame code)](https://github.com/paulober/MicroPico/blame/887d075ac4847db118be07327d53c7c3c31d5c0c/src/activator.mts#L1283), or if it is the PyBoard's [Pyboardrunner firing onExit](https://github.com/paulober/pyboard-serial-com/blame/2a9a07c098de624a015ca1dc9e877dffe4c68ebc/src/pyboardRunner.ts#L259) non-stop.

Hopefulle someone else managed to find the cause. 🙏

**Comment by migs35323** [comment] 2024-02-20 20:39
Just installed this extension, and come to look for this, when i open code it shows multiple warnings of the connection lost, i believe there should be improvements on this, it makes vscode a bit slower and awkard in general when trying to use other unrelated projects

**Comment by paulober** [comment] 2024-02-21 23:51
These unnecessary notifications should be fixed with the next patch. Thanks for the feedback.

**Closed** 2024-02-22 00:03 UTC
Labels: enhancement

**Comment by vbakke** [comment] 2024-02-26 11:58
Looks good when I tested just now. :) 👍
